In [ ]:
from data.get_data import get_dataframe
from data_processor.calculate_stats import calculate_statistics
from data_processor.data_categorising import categories_columns
from data_processor.data_cleaner import clean_data
from data_processor.fight_stats import finalProcessingForFighter, calculateAverages
from data_processor.data_types_fixes import check_and_process_data_type, drop_col_for_training

In [ ]:
og_df = get_dataframe('original.csv')

In [ ]:
cleaned_df = clean_data(og_df)

In [ ]:
stats_df = calculate_statistics(cleaned_df)

In [ ]:
processed_df = finalProcessingForFighter(stats_df)

In [ ]:
processed_df = check_and_process_data_type(processed_df)

In [ ]:
avg_df = calculateAverages(processed_df)

In [27]:
cat_df = categories_columns(avg_df)

In [28]:
df_for_training = drop_col_for_training(cat_df)

In [30]:
df_for_training = df_for_training.sort_index()
df_for_training

,Total_KD,Total_STR,Total_TD,Total_SUB,Round,Time,Target,Avg_Round_Time,Avg_Round,Fighter_code,Opp_code,Weight_Class_code
0,0,0,0,0,1.0,20.0,0,0.000000,0.000000,1786,2058,8
1,0,0,0,0,1.0,77.0,0,0.000000,0.000000,2009,1794,8
2,0,0,0,0,1.0,91.0,0,0.000000,0.000000,869,1886,8
3,0,0,0,0,1.0,67.0,0,0.000000,0.000000,1329,1160,8
4,0,0,0,0,1.0,67.0,0,0.000000,0.000000,1322,1008,8
...,...,...,...,...,...,...,...,...,...,...,...,...
14819,0,0,0,0,2.0,257.0,0,309.666667,2.333333,914,1943,5
14820,1,289,2,0,2.0,71.0,0,445.875000,3.750000,2358,994,10
14821,0,226,6,2,3.0,300.0,0,300.000000,3.000000,991,2299,13
14822,1,546,14,11,3.0,75.0,0,295.250000,3.250000,1249,1631,11
14823,2,468,28,0,1.0,64.0,0,266.909091,2.409091,224,181,6

In [36]:
x = df_for_training.drop('Target', axis=1)
x

,Total_KD,Total_STR,Total_TD,Total_SUB,Round,Time,Avg_Round_Time,Avg_Round,Fighter_code,Opp_code,Weight_Class_code
0,0,0,0,0,1.0,20.0,0.000000,0.000000,1786,2058,8
1,0,0,0,0,1.0,77.0,0.000000,0.000000,2009,1794,8
2,0,0,0,0,1.0,91.0,0.000000,0.000000,869,1886,8
3,0,0,0,0,1.0,67.0,0.000000,0.000000,1329,1160,8
4,0,0,0,0,1.0,67.0,0.000000,0.000000,1322,1008,8
...,...,...,...,...,...,...,...,...,...,...,...
14819,0,0,0,0,2.0,257.0,309.666667,2.333333,914,1943,5
14820,1,289,2,0,2.0,71.0,445.875000,3.750000,2358,994,10
14821,0,226,6,2,3.0,300.0,300.000000,3.000000,991,2299,13
14822,1,546,14,11,3.0,75.0,295.250000,3.250000,1249,1631,11
14823,2,468,28,0,1.0,64.0,266.909091,2.409091,224,181,6

In [39]:
y = df_for_training['Target']
y

0        0
1        0
2        0
3        0
4        0
        ..
14819    0
14820    0
14821    0
14822    0
14823    0
Name: Target, Length: 14764, dtype: int64