In [9]:
import os
import sys
import pandas as pd

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, PROJECT_ROOT)
os.chdir(PROJECT_ROOT)

from data.get_data import get_dataframe

In [10]:
df = get_dataframe("processed.csv")
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date', ascending=False)
df

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,Opp_TD,Opp_SUB,Round,Time,Target,Avg_Round_Time,Avg_Round
14763,Beneil Dariush,2023-12-02,Arman Tsarukyan,Lightweight,7,772,26,12,2,468,28,0,1.0,64.0,0,266.909091,2.409091
7367,Jalin Turner,2023-12-02,Bobby Green,Lightweight,5,416,4,7,4,1653,20,5,1.0,169.0,1,309.000000,2.900000
14752,Bobby Green,2023-12-02,Jalin Turner,Lightweight,4,1653,20,5,5,416,4,7,1.0,169.0,0,374.956522,3.521739
14753,Rob Font,2023-12-02,Deiveson Figueiredo,Bantamweight,7,1160,13,5,11,516,16,20,3.0,300.0,0,364.312500,4.062500
14754,Kelvin Gastelum,2023-12-02,Sean Brady,Welterweight,9,1040,19,2,1,313,14,4,3.0,103.0,0,372.238095,4.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7383,Scott Baker,1994-03-11,Remco Pardoel,Open Weight,0,0,0,0,0,1,0,1,1.0,401.0,0,0.000000,0.000000
7384,Alberta Cerra Leon,1994-03-11,Johnny Rhodes,Open Weight,0,0,0,0,0,4,0,0,1.0,591.0,0,0.000000,0.000000
7385,Robert Lucarelli,1994-03-11,Patrick Smith,Open Weight,0,0,0,0,0,1,0,0,1.0,170.0,0,0.000000,0.000000
7386,Thaddeus Luster,1994-03-11,Royce Gracie,Open Weight,0,0,0,0,1,26,3,3,1.0,292.0,0,0.000000,0.000000
7382,Minoki Ichihara,1994-03-11,Royce Gracie,Open Weight,0,0,0,0,1,24,2,1,1.0,308.0,0,0.000000,0.000000

In [11]:
fighter1 = "Khabib Nurmagomedov"
fighter2 = "Conor McGregor"

In [ ]:
fighter1_info = df[df['Fighter'].str.contains(fighter1, case=False)].head(1)

fighter1_info = fighter1_info[['Weight_Class', 'Total_KD', 
                               'Total_STR', 'Total_TD', 'Total_SUB', 
                               'Avg_Round_Time', 'Avg_Round']]

fighter1_info

,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Avg_Round_Time,Avg_Round
5768,Lightweight,2,679,59,8,226.75,3.0

In [17]:
fighter2_info = df[df['Fighter'].str.contains(fighter2, case=False)].head(1)

fighter2_info = fighter2_info[['Weight_Class', 'Total_KD', 
                               'Total_STR', 'Total_TD', 'Total_SUB', 
                               'Avg_Round_Time', 'Avg_Round']]

fighter2_info

,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Avg_Round_Time,Avg_Round
13509,Lightweight,13,572,5,0,218.461538,2.692308

In [5]:
import joblib

model = joblib.load("saved_models/RandomForestClassifierModel.joblib")