In [21]:
import os
import sys
import pandas as pd

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, PROJECT_ROOT)
os.chdir(PROJECT_ROOT)

from data.get_data import get_dataframe

In [2]:
df = get_dataframe("processed.csv")
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date', ascending=False)
df

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,...,Round,Time,Target,Avg_Round_Time,Avg_Round,Opp_Avg_Round_Time,Opp_Avg_Round,Fighter_code,Opp_code,Weight_Class_code
1177,Arman Tsarukyan,2023-12-02,Beneil Dariush,Lightweight,2,468,28,0,7,772,...,1.0,64.0,1,316.777778,3.777778,151.000000,2.000000,181,224,6
14403,Wellington Turman,2023-12-02,Jared Gooden,Welterweight,0,275,9,5,1,289,...,2.0,71.0,0,445.875000,3.750000,493.600000,5.000000,2358,994,10
6247,Jared Gooden,2023-12-02,Wellington Turman,Welterweight,1,289,2,0,0,275,...,2.0,71.0,1,493.600000,5.000000,559.333333,3.333333,1000,2340,10
2738,Cody Brundage,2023-12-02,Zach Reese,Middleweight,2,72,8,4,0,0,...,1.0,109.0,1,353.428571,3.000000,0.000000,0.000000,453,2398,7
2716,Clay Guida,2023-12-02,Joaquim Silva,Lightweight,6,1108,76,16,2,319,...,3.0,300.0,0,330.542857,3.771429,222.000000,3.500000,448,1098,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6314,Jason DeLucia,1994-03-11,David Levicki,Open Weight,0,0,1,0,0,0,...,1.0,733.0,0,0.000000,0.000000,0.000000,0.000000,1014,587,8
3570,David Levicki,1994-03-11,Jason DeLucia,Open Weight,0,0,0,0,0,0,...,1.0,733.0,0,0.000000,0.000000,0.000000,0.000000,588,1008,8
12019,Robert Lucarelli,1994-03-11,Patrick Smith,Open Weight,0,0,0,0,0,1,...,1.0,170.0,0,0.000000,0.000000,0.000000,0.000000,1947,1794,8
13481,Thaddeus Luster,1994-03-11,Royce Gracie,Open Weight,0,0,0,0,1,26,...,1.0,292.0,0,0.000000,0.000000,307.000000,1.285714,2215,1995,8
12679,Sean Daugherty,1994-03-11,Orlando Wiet,Open Weight,0,0,0,0,0,0,...,1.0,20.0,0,0.000000,0.000000,0.000000,0.000000,2075,1774,8

In [ ]:
fighter1 = "Khabib Nurmagomedov"
fighter2 = "Conor McGregor"

In [4]:
fighter1_info = df[df['Fighter'].str.contains(fighter1, case=False)].head(1)

fighter1_info = fighter1_info[['Weight_Class_code', 'Total_KD', 
                               'Total_STR', 'Total_TD', 'Total_SUB', 
                               'Avg_Round_Time', 'Avg_Round']]

fighter1_info

,Weight_Class_code,Total_KD,Total_STR,Total_TD,Total_SUB,Avg_Round_Time,Avg_Round
8264,6,2,679,59,8,226.75,3.0

In [ ]:
fighter2_info = df[df['Fighter'].str.contains(fighter2, case=False)].head(1)

fighter2_info = fighter2_info[['Weight_Class_code', 'Total_KD', 
                               'Total_STR', 'Total_TD', 'Total_SUB', 
                               'Avg_Round_Time', 'Avg_Round']]

fighter2_info

,Weight_Class_code,Total_KD,Total_STR,Total_TD,Total_SUB,Avg_Round_Time,Avg_Round
2862,6,13,572,5,0,218.461538,2.692308

In [10]:
fighter2_info['Total_SUB'].iloc[0]

np.int64(0)

In [16]:
data = {
    'Total_KD': fighter1_info['Total_KD'].iloc[0],
    'Total_STR': fighter1_info['Total_STR'].iloc[0],
    'Total_TD': fighter1_info['Total_TD'].iloc[0],
    'Total_SUB': fighter1_info['Total_SUB'].iloc[0],
    'Opp_KD': fighter2_info['Total_KD'].iloc[0],
    'Opp_STR': fighter2_info['Total_STR'].iloc[0],
    'Opp_TD': fighter2_info['Total_TD'].iloc[0],
    'Opp_SUB': fighter2_info['Total_SUB'].iloc[0],
    'Avg_Round_Time': fighter1_info['Avg_Round_Time'].iloc[0],
    'Avg_Round': fighter1_info['Avg_Round'].iloc[0],
    'Opp_Avg_Round_Time': fighter2_info['Avg_Round_Time'].iloc[0],
    'Opp_Avg_Round': fighter2_info['Avg_Round'].iloc[0],
    'Weight_Class_code': fighter1_info['Weight_Class_code'].iloc[0],
}

x_predict = pd.DataFrame(data, index=[0])
x_predict

,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,Opp_TD,Opp_SUB,Avg_Round_Time,Avg_Round,Opp_Avg_Round_Time,Opp_Avg_Round,Weight_Class_code
0,2,679,59,8,13,572,5,0,226.75,3.0,218.461538,2.692308,6

In [ ]:
import joblib

model = joblib.load("saved_models/RandomForestClassifierModel.joblib")

In [ ]:
win_prob = model.predict_proba(x_predict)

(np.float64(0.38243835056652126), np.float64(0.6175616494334787))