In [1]:
import os
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.insert(0, PROJECT_ROOT)
os.chdir(PROJECT_ROOT)

from data.get_data import get_dataframe, convert_to_csv
from data_processor.calculate_stats import calculate_statistics
from data_processor.data_categorising import categories_columns
from data_processor.data_cleaner import clean_data
from data_processor.fight_stats import finalProcessingForFighter, calculateAverages
from data_processor.data_types_fixes import check_and_process_data_type, drop_col_for_training

In [2]:
og_df = get_dataframe('original.csv')

In [3]:
cleaned_df = clean_data(og_df)

In [4]:
stats_df = calculate_statistics(cleaned_df)

In [5]:
processed_df = finalProcessingForFighter(stats_df)
processed_df

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,Opp_TD,Opp_SUB,Round,Time,Target
0,Orlando Wiet,1994-03-11 00:00:00.000,Sean Daugherty,Open Weight,0,0,0,0,0,0,0,0,1.0,0:20,0
1,Royce Gracie,1994-03-11 00:00:00.000,Patrick Smith,Open Weight,0,0,0,0,0,0,0,0,1.0,1:17,0
2,Harold Howard,1994-03-11 00:00:00.000,Remco Pardoel,Open Weight,0,0,0,0,0,0,0,0,1.0,1:31,0
3,Ken Shamrock,1994-03-11 00:00:00.000,Johnny Rhodes,Open Weight,0,0,0,0,0,0,0,0,1.0,1:07,0
4,Keith Hackney,1994-03-11 00:00:00.000,Jason DeLucia,Open Weight,0,0,0,0,0,0,0,0,1.0,1:07,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14819,Ihor Potieria,2023-12-02 00:00:00.000,Rodolfo Bellato,Light Heavyweight,1,64,0,0,0,0,0,0,2.0,4:17,0
14820,Wellington Turman,2023-12-02 00:00:00.000,Jared Gooden,Welterweight,0,275,9,5,1,289,2,0,2.0,1:11,0
14821,Jamey-Lyn Horth,2023-12-02 00:00:00.000,Veronica Hardy,Women's Flyweight,0,76,0,0,0,226,6,2,3.0,5:00,0
14822,Julia Avila,2023-12-02 00:00:00.000,Miesha Tate,Women's Bantamweight,1,142,2,1,1,546,14,11,3.0,1:15,0
14823,Beneil Dariush,2023-12-02 00:00:00.000,Arman Tsarukyan,Lightweight,7,772,26,12,2,468,28,0,1.0,1:04,0

In [6]:
processed_df = check_and_process_data_type(processed_df)

In [7]:
avg_df = calculateAverages(processed_df)
avg_df

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,Opp_TD,Opp_SUB,Round,Time,Target,Avg_Round_Time,Avg_Round,Opp_Avg_Round_Time,Opp_Avg_Round
13859,AJ Dobson,2022-02-12,Jacob Malkoun,Middleweight,0,0,0,0,0,27,8,2,3.0,300.0,0,0.00,0.000000,0.000000,0.000000
14238,AJ Dobson,2022-10-22,Armen Petrosyan,Middleweight,0,52,0,0,0,158,0,0,3.0,300.0,0,600.00,6.000000,0.000000,0.000000
7249,AJ Dobson,2023-08-12,Tafon Nchukwi,Middleweight,0,110,3,0,1,340,4,0,3.0,300.0,1,600.00,6.000000,0.000000,0.000000
13913,AJ Fletcher,2022-03-12,Matthew Semelsberger,Welterweight,0,0,0,0,3,188,2,1,3.0,300.0,0,0.00,0.000000,0.000000,0.000000
14165,AJ Fletcher,2022-08-20,Ange Loosa,Welterweight,0,34,4,2,0,88,0,0,3.0,300.0,0,600.00,6.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,Zubaira Tukhugov,2020-02-22,Kevin Aguilar,Featherweight,1,147,13,0,1,177,1,0,1.0,201.0,1,352.20,3.200000,480.000000,4.800000
13170,Zubaira Tukhugov,2020-09-26,Hakeem Dawodu,Featherweight,3,175,13,0,1,316,0,0,3.0,300.0,0,327.00,2.833333,369.666667,3.888889
6321,Zubaira Tukhugov,2021-10-30,Ricardo Ramos,Featherweight,3,210,14,0,2,256,17,4,3.0,300.0,1,366.00,3.285714,282.300000,2.300000
14374,Zubaira Tukhugov,2023-02-11,Elves Brener,Lightweight,3,287,16,0,0,0,0,0,3.0,300.0,0,357.75,3.250000,219.000000,2.000000
13721,Zviad Lazishvili,2021-10-23,Jonathan Martinez,Bantamweight,0,0,0,0,5,397,3,0,3.0,300.0,0,0.00,0.000000,313.500000,3.416667

In [8]:
cat_df = categories_columns(avg_df)

In [9]:
df_for_training = drop_col_for_training(cat_df)

In [10]:
df_for_training = df_for_training.sort_index()
df_for_training

,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,Opp_TD,Opp_SUB,Target,Avg_Round_Time,Avg_Round,Opp_Avg_Round_Time,Opp_Avg_Round,Weight_Class_code
0,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.0,0.0,8
1,0,0,0,0,0,0,0,0,0,0.000000,0.000000,170.0,1.0,8
2,0,0,0,0,0,0,0,0,0,0.000000,0.000000,747.0,1.0,8
3,0,0,0,0,0,0,0,0,0,0.000000,0.000000,591.0,1.0,8
4,0,0,0,0,0,0,0,0,0,0.000000,0.000000,454.5,1.5,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14819,1,64,0,0,0,0,0,0,0,309.666667,2.333333,0.0,0.0,5
14820,0,275,9,5,1,289,2,0,0,445.875000,3.750000,493.6,5.0,10
14821,0,76,0,0,0,226,6,2,0,300.000000,3.000000,486.5,5.5,13
14822,1,142,2,1,1,546,14,11,0,295.250000,3.250000,313.0,4.0,11
14823,7,772,26,12,2,468,28,0,0,266.909091,2.409091,0.0,0.0,6

In [11]:
x = df_for_training.drop('Target', axis=1)

In [12]:
y = df_for_training['Target']

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
pipe = Pipeline([
    ("classifier", RandomForestClassifier(
        n_estimators=500,
        random_state=42,
        class_weight="balanced_subsample",
        max_depth=8,
        min_samples_leaf=8,
        min_samples_split=20,  
        bootstrap=True,
        oob_score=False,
        n_jobs=-1,
    ))
])

In [16]:
# param_grid = {
#     "classifier__max_features": ["sqrt", "log2", 0.3, 0.5, 0.7],
#     "classifier__criterion": ["gini", "entropy", "log_loss"],
#     "classifier__max_samples": [None, 0.6, 0.8, 1.0],
# }

grid = GridSearchCV(pipe, {}, cv=2, scoring='roc_auc', n_jobs=-1)

In [17]:
grid.fit(x_train, y_train)

GridSearchCV(cv=2,
             estimator=Pipeline(steps=[('classifier',
                                        RandomForestClassifier(class_weight='balanced_subsample',
                                                               max_depth=8,
                                                               min_samples_leaf=8,
                                                               min_samples_split=20,
                                                               n_estimators=500,
                                                               n_jobs=-1,
                                                               random_state=42))]),
             n_jobs=-1, param_grid={}, scoring='roc_auc')

In [18]:
y_pred = grid.predict(x_test)

In [19]:
from sklearn import metrics

acc = metrics.accuracy_score(y_test, y_pred)
prec = metrics.precision_score(y_test, y_pred)
recall = metrics.recall_score(y_test, y_pred)

acc, prec, recall

(0.5882153741957331, 0.5894279507603186, 0.556390977443609)

In [20]:
y_proba = grid.predict_proba(x_test)[:, 1]
roc_auc = float(metrics.roc_auc_score(y_test, y_proba))
roc_auc

0.614207957355255

In [21]:
import pandas as pd

importances = grid.best_estimator_.named_steps["classifier"].feature_importances_

feat_imp = pd.DataFrame({
    "feature": x.columns,
    "importance": importances
}).sort_values("importance", ascending=False)

feat_imp

               feature  importance
10  Opp_Avg_Round_Time    0.168200
11       Opp_Avg_Round    0.135761
1            Total_STR    0.111790
8       Avg_Round_Time    0.102726
5              Opp_STR    0.097203
9            Avg_Round    0.069181
2             Total_TD    0.067437
6               Opp_TD    0.057133
12   Weight_Class_code    0.056076
7              Opp_SUB    0.036125
3            Total_SUB    0.034227
0             Total_KD    0.033308
4               Opp_KD    0.030833

In [22]:
import joblib
from pathlib import Path

save_dir = Path("saved_models")
save_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(grid, save_dir / 'RandomForestClassifierModel.joblib')

['saved_models/RandomForestClassifierModel.joblib']

In [23]:
model = joblib.load("saved_models/RandomForestClassifierModel.joblib")

In [24]:
y_loaded_pred = model.predict(x_test)

In [25]:
cat_df[cat_df['Weight_Class'] == 'Lightweight'].head(1)

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Opp_KD,Opp_STR,...,Round,Time,Target,Avg_Round_Time,Avg_Round,Opp_Avg_Round_Time,Opp_Avg_Round,Fighter_code,Opp_code,Weight_Class_code
13398,Aalon Cruz,2021-03-06,Uros Medic,Lightweight,0,2,0,0,0,0,...,1.0,100.0,0,170.0,2.0,0.0,0.0,2,2287,6