In [18]:
import pandas as pd
import sys
sys.path.append("..")

from data.get_data import get_dataframe

df = get_dataframe("ufc_with_career_stats.csv")

In [ ]:
cols = ["Fighter", "Opp", "Date", "KD", "STR", "TD", "SUB", "Weight_Class", "Winner"]

fighter_1 = df[[
    "Fighter 1",
    "Fighter 2",
    "Date",
    "Fighter_1_total_KD",
    "Fighter_1_total_STR",
    "Fighter_1_total_TD",
    "Fighter_1_total_SUB",
    "Weight_Class",
    "Winner"
]].copy()
fighter_1.columns = cols
fighter_1["Target"] = (fighter_1["Fighter"] == fighter_1["Winner"]).astype(int)
fighter_1["Fights"] = 1

fighter_2 = df[[
    "Fighter 2",
    "Fighter 1",
    "Date",
    "Fighter_1_total_KD",
    "Fighter_1_total_STR",
    "Fighter_1_total_TD",
    "Fighter_1_total_SUB",
    "Weight_Class",
    "Winner"
]].copy()
fighter_2.columns = cols
fighter_2["Target"] = (fighter_2["Fighter"] == fighter_2["Winner"]).astype(int)
fighter_2["Fights"] = 1

fighters = pd.concat([fighter_1, fighter_2], ignore_index=True)

fighters

,Fighter,Opp,Date,KD,STR,TD,SUB,Weight_Class,Winner,Target,Fights
0,Orlando Wiet,Sean Daugherty,1994-03-11 00:00:00.000,0,0,0,0,Open Weight,Patrick Smith,0,1
1,Royce Gracie,Patrick Smith,1994-03-11 00:00:00.000,0,0,0,0,Open Weight,Keith Hackney,0,1
2,Harold Howard,Remco Pardoel,1994-03-11 00:00:00.000,0,0,0,0,Open Weight,Royce Gracie,0,1
3,Ken Shamrock,Johnny Rhodes,1994-03-11 00:00:00.000,0,0,0,0,Open Weight,Royce Gracie,0,1
4,Keith Hackney,Jason DeLucia,1994-03-11 00:00:00.000,0,0,0,0,Open Weight,Patrick Smith,0,1
...,...,...,...,...,...,...,...,...,...,...,...
14829,Jonathan Goulet,Mike Swick,NaN,3,280,8,5,Welterweight,Mike Swick,0,1
14830,NaN,Frank Hamaker,NaN,0,0,0,0,NaN,Scott Morris,0,1
14831,NaN,Johnny Rhodes,NaN,0,8,1,1,NaN,NaN,0,1
14832,NaN,Patrick Smith,NaN,0,22,0,0,NaN,NaN,0,1
14833,NaN,Scott Morris,NaN,0,0,0,0,NaN,NaN,0,1

In [34]:
fighter_stats = (
    fighters.loc[:, ["Fighter", "Date", "Opp", "Weight_Class", "KD", "STR", "TD", "SUB", "Target"]]
    .drop_duplicates(subset=["Fighter", "Date"])
    .rename(columns={
        "KD": "Total_KD",
        "STR": "Total_STR",
        "TD": "Total_TD",
        "SUB": "Total_SUB"
    })
)

fighter_stats

,Fighter,Date,Opp,Weight_Class,Total_KD,Total_STR,Total_TD,Total_SUB,Target
0,Orlando Wiet,1994-03-11 00:00:00.000,Sean Daugherty,Open Weight,0,0,0,0,0
1,Royce Gracie,1994-03-11 00:00:00.000,Patrick Smith,Open Weight,0,0,0,0,0
2,Harold Howard,1994-03-11 00:00:00.000,Remco Pardoel,Open Weight,0,0,0,0,0
3,Ken Shamrock,1994-03-11 00:00:00.000,Johnny Rhodes,Open Weight,0,0,0,0,0
4,Keith Hackney,1994-03-11 00:00:00.000,Jason DeLucia,Open Weight,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
14826,Jamey-Lyn Horth,2023-12-02 00:00:00.000,Veronica Hardy,Women's Flyweight,0,226,6,2,0
14827,Julia Avila,2023-12-02 00:00:00.000,Miesha Tate,Women's Bantamweight,1,546,14,11,0
14828,Beneil Dariush,2023-12-02 00:00:00.000,Arman Tsarukyan,Lightweight,2,468,28,0,0
14829,Jonathan Goulet,NaN,Mike Swick,Welterweight,3,280,8,5,0
14830,NaN,NaN,Frank Hamaker,NaN,0,0,0,0,0